
version: '3'

services: 
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-local
    ports:
      - 27017:27017

  compass_webui:
    image: haohanyang/compass-web
    environment:
      - CW_MONGO_URI=mongodb://mongo:27017
    ports:
      - 8080:8080
    depends_on:
      - mongo